In [4]:
import numpy as np
abc= np.zero(10)
abc[4]= 1
print (abc)

AttributeError: module 'numpy' has no attribute 'zero'

In [3]:
# Create a null vector of size 10 but the fifth value which is 1.


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
import numpy as np
abc= np.zeros(10)
abc[4]= 1
print (abc)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
# 2. Create a vector with values ranging from 10 to 49.
ab=np.arange(10,50)
print(ab)



[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
# Create a 3x3 matrix with values ranging from 0 to 8
bbb = np.arange(9).reshape(3,3)
print (bbb)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
non_zero = np.nonzero([1,2,0,0,4,0])
print(non_zero)

(array([0, 1, 4], dtype=int64),)


In [11]:
# Create a 10x10 array with random values and find the minimum and maximum values.
arrr = np.random.random((10,10))
arrrmin, arrrmax = arrr.min(), arrr.max()
print(arrrmin, arrrmax)

0.005125639811668581 0.9824165132436609


In [12]:
# Create a random vector of size 30 and find the mean value.
h = np.random.random(10)
s = h.mean()
print (s)


0.3255092071054001
